name: reteno_plugin
description: The Reteno Flutter Plugin for Mobile Customer Engagement and Analytics solutions
version: 1.8.7
homepage: https://github.com/reteno-com/reteno-flutter
issue_tracker: https://github.com/reteno-com/reteno-flutter/issues?q=is%3Aissue+is%3Aopen
documentation: https://docs.reteno.com/reference/flutter-sdk

false_secrets:
 - example/

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  pigeon: ^26.0.0
  mocktail: ^1.0.3

flutter:
  plugin:
    platforms:
      android:
        package: com.reteno.reteno_plugin
        pluginClass: RetenoPlugin
      ios:
        pluginClass: RetenoPlugin

